---
- hosts: localhost
  gather_facts: true

  vars:
    kubectl_url: https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl
    helm_url: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz

  tasks:

      # Load variables
    - name: Load default config variables
      include_vars: 00-variables.yaml

    - name: Add EPEL repository
      ansible.builtin.yum:
        name: epel-release
      ignore_errors: true
      when: ansible_os_family|lower == "redhat"

    - name: Install software
      package:
        name: '{{ item }}'
        state: present
      ignore_errors: true
      loop:
        - dos2unix
        - coreutils
        - git
        - gtk3
        - java-21-openjdk
        - openjdk-21-jdk-headless # Ubuntu
        - jq
        - openssl
        - openssl-libs
        - libssl-dev # Ubuntu
        - python3-pip
        - python3-jmespath
        - sshpass
        - tar
        - unzip
        - wget
        - yq
        - xmlstarlet
        - zip

    - name: Update ansible.cfg [defaults]
      ini_file:
        path: '{{ ansible_cfg_file }}'
        section: defaults
        option: '{{ item.setting }}'
        value: '{{ item.value }}'
      loop:
        - { setting: "bin_ansible_callbacks", value: "True" }
        - { setting: "stdout_callback", value: "yaml" }
        - { setting: "host_key_checking", value: "False" }

    - name: Update ansible.cfg [ssh_connection]
      ini_file:
        path: '{{ ansible_cfg_file }}'
        section: ssh_connection
        option: '{{ item.setting }}'
        value: '{{ item.value }}'
      loop:
        - { setting: "ssh_args", value: "-o ControlMaster=auto" }
        - { setting: "retries", value: "3" }
        - { setting: "pipelining", value: "True" }

    - name: Install helm
      unarchive:
        src: '{{ helm_url }}'
        dest: /usr/local/bin
        remote_src: true
        extra_opts:
          - --strip=1
          - --no-anchored
          - helm
        mode: "0755"
      when: install_helm|bool

    - name: Install kubectl
      get_url:
        url: '{{ kubectl_url }}'
        dest: /usr/local/bin
        mode: "0755"
      when: install_kubectl|bool
