---
- hosts: localhost

  tasks:

    - name: Create {{ jenkins_dir }}
      file:
        name: "{{ jenkins_dir }}"
        state: directory

    - name: Create casc config file
      ansible.builtin.template:
        src: casc-config.yaml.j2
        dest: "{{ jenkins_dir }}/casc/"

    - name: Create casc security config file
      ansible.builtin.template:
        src: casc-security.yaml.j2
        dest: "{{ jenkins_dir }}/casc/"
      when: jenkins_login_user|length > 0

    - name: Create pipeline creation groovy script
      template:
        src: 'templates/create-pipelines.groovy.j2'
        dest: '{{ jenkins_dir }}/casc/create_pipelines.groovy'

    - name: Create empty tokens.json
      ansible.builtin.file:
        path: '{{ jenkins_dir }}/jenkins_home/casc/tokens.json'
        state: touch

    - name: Install Jenkins
      package:
        name: jenkins
        state: present
      when: install_jenkins|bool

    - name: Start and enable Jenkiins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: true
