---
- hosts: localhost

  tasks:

      # Load variables
    - name: Load default config variables
      include_vars: 00-variables.yaml

    - name: Run the Common Services extractor script
      shell: set -o pipefail && echo y | ./{{ hp_installer }}

    - name: Move the helix-on-prem-deployment-manager directory to the base directory
      command: mv helix-on-prem-deployment-manager /home/{{ git_user }}

    - name: Include HP version specific tasks if they exist
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files:
            - tasks/hp-{{ hp_version }}-tasks.yaml
          skip: true
