# Demo hitt.conf for VHS tapes (not used in production).
# REQUIRED SETTINGS
HP_NAMESPACE=demo-hp
IS_NAMESPACE=demo-is
IS_CUSTOMER_SERVICE=demo
IS_ENVIRONMENT=dev
CDE_NAMESPACE=

# OPTIONAL SETTINGS
JENKINS_USERNAME=''
JENKINS_PASSWORD=''
JENKINS_HOSTNAME=localhost
JENKINS_PROTOCOL=http
JENKINS_PORT=8080
